name = "glormat"
version = "1.0.0"

description = "A simple, readable string formatting library for Gleam!"
licences = ["Apache-2.0"]
repository = { type = "github", user = "SaphiraKai", repo = "glormat" }
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
